### ISSUE TITLE
Why is this link (https://beycodk.student.fdnd.nl/article/1) not working directly?

### ISSUE THREAD

**Issue by suustenvoorde** [DaanKorver/chippr-beyco-newspage#10]

**Comment by DaanKorver** [comment]
Because its rendered client side and the github pages doesn't let the request go directly through the index.html file.

See 
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations 
https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually
